settings:
  title: 'Status Page'
  url: 'https://status.renlord.com' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: renlord-com
    name: Homepage (renlord.com)
    url: 'https://renlord.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: work611-renlord-com
    name: Melbz Research Host 🇦🇺
    url: 'https://work611.renlord.com/status_check'
    method: GET
    expectStatus: 204
    linkable: false

  - id: sg-home
    name: Home Gateway 🇸🇬
    url: 'https://cloud.rny.app'
    method: GET
    expectStatus: 302
    linkable: false

  - id: email
    name: Email Host
    url: 'https://mail.katmail.xyz/status_check'
    method: GET
    expectStatus: 204
    linkable: false
